### PR TITLE
Correct use of GROUP BY

### LINKED ISSUE #693: Undefined value for bare column sql group by
In some of the queries of the allocator a "group by" clause is used with "bare columns" (see https://www.sqlite.org/lang_select.html section 2.5).  This will lead to potentially incorrect results when e.g. selecting a rectangle starting at a specified coordinate or finding all possible rectangles including those with wrap arounds.

### PR DESCRIPTION
**Pull request by dkfellows**
This makes the code use `GROUP BY` and aggregates correctly, not relying on the DB to select a special row from the group for us. We simply can't be sure that the DB will choose correctly. Fortunately, we have indices already set up that let us efficiently handle this by using the coordinates of the root of the group (which we were grouping by) and inflating that back to the ID of the board at that point.

The report handling just looked wrong.

This fixes #693

### CODE REVIEW

File: SpiNNaker-allocserv/src/main/resources/queries/find_rectangle_at.sql [hunk 1]
```diff
@@ -32,19 +32,29 @@ WITH RECURSIVE
 		LIMIT (SELECT height FROM m)),
 	-- Form the sequences into grids of points
 	c(x,y,z) AS (SELECT x, y, z FROM cx, cy, triad),
-	g(x,y) AS (SELECT x, y FROM gx, gy)
+	g(x,y) AS (SELECT x, y FROM gx, gy),
+	-- Root coords and number of boards available from that point
+	-- NB: Can't use board ID safely as we are using a GROUP BY
+	root(x,y,z,available) AS (
+		SELECT g.x AS x, g.y AS y, 0 AS z,
+			SUM(boards.may_be_allocated) AS available
```
Comment (rowleya) [inline SpiNNaker-allocserv/src/main/resources/queries/find_rectangle_at.sql:40]: I think this needs to be bs.may_be_allocated

File: SpiNNaker-allocserv/src/main/resources/queries/get_reported_boards.sql [hunk 2]
```diff
@@ -14,17 +14,22 @@
 -- along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 -- Get boards with more problem reports than a critical threshold
+WITH report_counts AS (
+	SELECT
+		board_reports.board_id,
+		COUNT(board_report.report_id) AS num_reports
```
Comment (rowleya) [inline SpiNNaker-allocserv/src/main/resources/queries/get_reported_boards.sql:20]: This should be board_reports.report_id

**Review by rowleya — CHANGES_REQUESTED** [review]
Couple of fixes to do

**Review by rowleya — APPROVED** [review]
