### PR TITLE
Demystify magic numbers

### LINKED ISSUE #166: MAGIC1 MAGIC2 in FloodFillDATA, END, START
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
these are cloned, move to constant place and use
============================

What do you see that is wrong?

What do you think it should do instead?

What version of our software are you using?
master
-------------------------------------------

### PR DESCRIPTION
**Pull request by dkfellows**
fixes #166

### CODE REVIEW

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPRequest.java [hunk 1]
```diff
@@ -191,4 +192,48 @@ public BMPResponse(String operation, SCPCommand command,
...
 		}
 	}
+
+	/**
+	 * A BMP response that contains a payload of interest.
+	 *
+	 * @param <T>
+	 *            The type of the parsed payload.
+	 */
+	public abstract static class PayloadedResponse<T> extends BMPResponse
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPRequest.java:202]: One of the things this PR does is to make the common pattern of handling the parsing of a response its own thing. This allows for some simplification of the higher levels of the transceiver.

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/SerialVector.java [hunk 2]
```diff
@@ -26,25 +28,28 @@
  * BMP_INFO} call with argument {@link BMPInfo#SERIAL SERIAL}.
  * <p>
  * See {@code cmd_bmp_info()} in {@code bmp_cmd.c}.
+ *
+ * @see ReadSerialVector
  */
 @UsedInJavadocOnly(SCPCommand.class)
 public class SerialVector {
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/SerialVector.java:35]: This class has grown the features that the other copy of it had.

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/ApplicationStop.java [hunk 3]
```diff
@@ -28,37 +29,51 @@
...
-	private static final int MAGIC2 = 5;
+	private static final int ADD_ID = 1;
 
-	private static final int MAGIC3 = 0x3f;
+	private static final int ALL_LINKS = 0x3f;
 
-	private static int argument1() {
-		return MAGIC1 << BYTE2;
+	private static int key() {
+		return (NN_CMD_SIG0 << BYTE3) | (FORWARD << BYTE2) | (RETRY << BYTE1);
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/ApplicationStop.java:55]: If you were to say that signals are a complicated mess, I'd be forced to agree enthusiastically.

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/PayloadedResponse.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+/**
+ * A response that holds a payload.
+ *
+ * @author Donal Fellows
+ * @param <T>
+ *            The type of parsed payload value.
+ * @param <E>
+ *            The type of exception thrown by the payload parser.
+ */
+public abstract class PayloadedResponse<T, E extends Exception>
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/PayloadedResponse.java:35]: Exact equivalent of same class for BMP messages. See notes above.

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPCommand.java [hunk 5]
```diff
@@ -77,35 +77,73 @@ public enum SCPCommand implements CommandCode {
...
+	 */
+	@Deprecated(forRemoval = true)
 	CMD_TUBE(64);
 
+	/**
+	 * Read FPGA's memory/registers. BMP-only operation.
+	 * <p>
+	 * Same as {@link #CMD_LINK_READ} but used differently.
+	 */
+	public static final SCPCommand CMD_FPGA_READ = CMD_LINK_READ;
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPCommand.java:138]: I've added these aliases because that matches what the BMP source code says better.

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPCommandProcess.java [hunk 6]
```diff
@@ -137,6 +137,35 @@ <T extends BMPResponse> T execute(BMPRequest<T> request)
...
+	 *            The request to send.
+	 * @return The successful response to the request.
+	 * @throws IOException
+	 *             If the communications fail
+	 * @throws ProcessException
+	 *             If the other side responds with a failure code
+	 * @throws InterruptedException
+	 *             If the communications were interrupted.
+	 */
+	<T, R extends BMPRequest.PayloadedResponse<T>> T call(BMPRequest<R> request)
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPCommandProcess.java:159]: This, despite the slightly ferocious type, is a simplified interface that does a normal synchronous call of a BMP operation and returns the payload from the result (on success). The type constraint just means that it can only be used with messages that expect a payload in their response. (There's similar stuff for the SCP process base.)

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/GetMachineProcess.java [hunk 7]
```diff
@@ -135,19 +137,19 @@ private static int clamp(int value, Integer limit) {
 	Machine getMachineDetails(HasChipLocation bootChip, MachineDimensions size)
 			throws IOException, ProcessException, InterruptedException {
 		// Get the P2P table; 8 entries are packed into each 32-bit word
-		var p2pColumnData = new ArrayList<ByteBuffer>();
-		for (int column = 0; column < size.width; column++) {
-			p2pColumnData.add(synchronousCall(new ReadMemory(bootChip,
-					ROUTER_P2P.add(getColumnOffset(column)),
-					getNumColumnBytes(size.height))).data);
-			// TODO work out why multiple calls at once is a problem
+		var p2pColumnData = new ByteBuffer[size.width];
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/GetMachineProcess.java:140]: We accumulate into an array so that we can easily do the reads out of order.

File: SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/Utils.java [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+	/**
+	 * Convert a word to a buffer that could form part of a message understood
+	 * by SpiNNaker.
+	 *
+	 * @param value
+	 *            The value to put in the buffer as a single 32-bit word.
+	 * @return The buffer, flipped. The buffer is writable and has a backing
+	 *         array.
+	 */
+	public static ByteBuffer wordAsBuffer(int value) {
```
Comment (dkfellows) [inline SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/Utils.java:41]: This pattern cropped up in a few places. I factored it out.
